// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:wyw/modules/download/download_module.dart';
import 'package:wyw/services/storage/history_entry.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DownloadEpisodeAdapter());
    registerAdapter(DownloadRecordAdapter());
    registerAdapter(HistoryEntryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DownloadEpisodeAdapter());
    registerAdapter(DownloadRecordAdapter());
    registerAdapter(HistoryEntryAdapter());
  }
}
